# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b3998478eda281789ccde71b731ffec2424586710cee856e7fa35dcda576769c2baceb8f360e5eef8a01f856f99c23f62a91b6ab0502b660db0cb1ddf5eeeed

test:
  secret_key_base: 30e3fa40b93b0ac05d8d5cd1a78e4787adfcf9517b23f22f4ff7e4455d5b1da8f40a21b0f781a6015ccc8b21640697539e95bc46cc1b26c90346bc6a6e3fc51c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
